### ISSUE TITLE
Feature: auto-remove orphaned clients

### ISSUE THREAD

**Issue by ChrisTerBeke** [ChrisTerBeke/nomad-on-gcp#14]
Old clients stay in the list (marked as unavailable). They should be cleaned up automatically.

**Comment by bschaatsbergen** [comment]
There's a setting in the autopilot configuration named [cleanup_dead_servers](https://developer.hashicorp.com/nomad/docs/configuration/autopilot#cleanup_dead_servers) which should address this issue. Autopilot was added under 8c5433f48ef72d30e9fc45aad73d80ae5034b51a
