### ISSUE TITLE
Feature: client auto-scaling based on planned allocations instead of actual CPU usage

### ISSUE THREAD

**Issue by ChrisTerBeke** [ChrisTerBeke/nomad-on-gcp#3]
Currently the cluster doesn't scale up even when all clients are fully allocated, leaving no room for new allocations. Also see https://developer.hashicorp.com/nomad/tools/autoscaling/agent/high_availability.

**Comment by ChrisTerBeke** [comment]
We could run Prometheus to capture the metrics, then export them to GCP (monitoring has Prometheus built-in nowadays), then create scaling rules on those metrics.

**Comment by bschaatsbergen** [comment]
Working on adding Prometheus in #15 first

**Comment by ChrisTerBeke** [comment]
Fixed by using open telemetry collector, GCP managed prometheus and metrics-based auto scaler config.
