### ISSUE TITLE
Improve: simpler base image

### ISSUE THREAD

**Issue by ChrisTerBeke** [ChrisTerBeke/nomad-on-gcp#5]
Currently using Ubuntu because it comes with `cloud-init` pre-installed. Let's try Container Optimize OS as well.

**Comment by ChrisTerBeke** [comment]
Tested manually in GCP with COS. Many tiny things to fix, but conceptually this works fine.

**Comment by bschaatsbergen** [comment]
Reopened this @ChrisTerBeke, since we still have the COS code in the repository and we should try to see whether we stick with Ubuntu or move to COS.

**Comment by ChrisTerBeke** [comment]
I have removed the COS code (it's still in the history of course) because I think it's a diminishing returns game. Every feature we want to add (CSI, CNI, etc) will require a lot more work in a COS environment. Probably better to pre-bake a Debian/ubuntu image with all the stuff we now run during `cloud-init` preinstalled to speed up boot times.

**Comment by bschaatsbergen** [comment]
Thanks for elaborating, Packer template it is.
