### ISSUE TITLE
Feature: cluster DNS

### ISSUE THREAD

**Issue by ChrisTerBeke** [ChrisTerBeke/nomad-on-gcp#6]
So we can reach talk to other services using an FQDN instead of IP addresses.

**Comment by ChrisTerBeke** [comment]
Probably not needed if we can route internal requests via Traefik as well.

**Comment by bschaatsbergen** [comment]
Fixed with traefik (in 1e2e3f3b764cb566257d240eb589745bc261b0a2) and the global load balancer for ingress traffic (done through 6e926e5)
