### ISSUE TITLE
Feature: persistent volumes

### ISSUE THREAD

**Issue by ChrisTerBeke** [ChrisTerBeke/nomad-on-gcp#7]
Mount persistent volumes on jobs using GCE disk driver.

**Comment by ChrisTerBeke** [comment]
We probably need to run a job for the CSI driver for GCE persistent disks.

**Comment by bschaatsbergen** [comment]
CSI driver support got added through: https://github.com/ChrisTerBeke/nomad-on-gcp/commit/514b0cdf36d479992ca1b1197aa4b121fe095c71
